added tests for ETL
torquem-ch/silkworm pull request #125
Opened 2020-12-23 14:46 UTC by Giulio2002

2020-12-23 14:47 UTC, Giulio2002 commented
#122

2020-12-23 16:09 UTC, yperbasis requested changes

2020-12-23 16:09 UTC, yperbasis commented on db/silkworm/etl/collector_test.cpp
> +    boost::filesystem::create_directory("temp");
Better use TemporaryDirectory again. TemporaryDirectory creates a fresh unique temporary dir and automatically cleans it up.

2020-12-23 16:09 UTC, yperbasis commented on db/silkworm/etl/collector_test.cpp
> +TEST_CASE("collect_and_load") {
Code duplication! Is transform function the only difference between these two tests? Extract a common function that takes transform function as an argument and call it twice with different transform functions.

2020-12-23 16:19 UTC, yperbasis commented on db/silkworm/etl/collector_test.cpp
> +    auto collector{Collector("temp", 1600)};    // 100 entries per file
```suggestion
    auto collector{Collector("temp", 16 * 100)};    // 100 entries per file (each entry is 16 bytes)
```

2020-12-24 10:23 UTC, yperbasis approved these changes

2021-01-07 15:38 UTC, merged