(WIP) added unique ids to files
torquem-ch/silkworm pull request #143
Opened 2021-01-24 15:09 UTC by Giulio2002

2021-01-25 11:42 UTC, Giulio2002 commented
This one is ready, @AndreaLanfranchi

2021-01-25 11:49 UTC, AndreaLanfranchi requested changes

2021-01-25 11:49 UTC, AndreaLanfranchi commented on db/silkworm/etl/file_provider.cpp
> +    fs::path path{fs::path(working_path) / fs::path("tmp-" + std::to_string(rand()))};
I don't think `rand()` provides any guarantee of uniqueness.
See for instance here where you discard values already provided by rand
https://github.com/torquem-ch/silkworm/blob/master/db/silkworm/etl/collector_test.cpp#L30-L48

As we may use Collector in several instances (might happen also amongst different threads) I'd suggest to go for something which provides a more robust self-containing uniqueness. Maybe explore Boost::Uuid ... create a unique value on Collector contructor and replace literal `tmp` with that value.

2021-01-29 20:30 UTC, AndreaLanfranchi approved these changes

2021-01-31 12:32 UTC, merged