(WIP) added unwind for execution stage
torquem-ch/silkworm pull request #264
Opened 2021-06-15 17:48 UTC by Giulio2002

2021-06-16 12:05 UTC, yperbasis commented
Can you please add some tests? That's a good engineering practice.

2021-06-17 09:07 UTC, Giulio2002 commented
@yperbasis I plan on doing that but I need to test it on an actual erigon node, which unfortunately runs on mdbx

2021-06-17 09:21 UTC, yperbasis commented
> @yperbasis I plan on doing that but I need to test it on an actual erigon node first (before writing tests), which unfortunately runs on mdbx

If you use Erigon version 2021.06.03-alpha or earlier, you can run it in lmdb mode with
```
--database lmdb
```
(see the comment in https://github.com/ledgerwatch/erigon/releases/tag/v2021.05.04)

Also, for unit tests you can create artificial transactions, execute them, unwind the execution, and check that the state changes are unwound – no need for Erigon. For an example, see `core/silkworm/execution/execution_test.cpp`

https://github.com/CoinCulture/evm-tools/blob/master/analysis/guide.md is a useful resource.

2021-06-26 11:05 UTC, yperbasis requested changes

2021-06-26 11:05 UTC, yperbasis commented on db/silkworm/stagedsync/stage_execution.cpp
> +    while (!rc) {
Does not look right to me. When `rc != 0` (apart from `MDB_NOTFOUND`), it is an error and we want to break the loop instead of continuing.

2021-06-29 22:18 UTC, Giulio2002 commented
Now i am pretty sure it works

2021-06-30 11:41 UTC, yperbasis commented on cmd/CMakeLists.txt
> +  target_link_libraries(unwind_execution PRIVATE silkworm_db silkworm_tg_api CLI11::CLI11)
`silkworm_tg_api` is probably unnecessary

2021-06-30 13:51 UTC, yperbasis approved these changes

2021-06-30 13:51 UTC, yperbasis commented on db/silkworm/db/tables.hpp
> +constexpr lmdb::TableConfig kCallTraceSet{"CallTraceSet", MDB_DUPSORT};
Please include `kCallTraceSet`  into `kTables`

2021-06-30 13:51 UTC, yperbasis commented on db/silkworm/stagedsync/stage_execution.cpp
> +        Bytes key(static_cast<unsigned char*>(mdb_key.mv_data), mdb_key.mv_size);
Better use `db::from_mdb_val` as in
```
Bytes key(db::from_mdb_val(mdb_key));
```

2021-06-30 22:42 UTC, Giulio2002 commented
now it should be all good, merge whenever you want

2021-07-01 07:49 UTC, merged