(WIP) added unwind hashstate
torquem-ch/silkworm pull request #278
Opened 2021-07-07 15:43 UTC by Giulio2002

2021-07-08 13:35 UTC, AndreaLanfranchi requested changes

2021-07-08 13:35 UTC, AndreaLanfranchi commented on libmdbx/mdbx.h
> +#define MDBX_DATANAME "mdbx.dat"
Please revert this.
We can't change MDBX defs as they would get overwritten when MDBX code is updated

2021-07-11 17:15 UTC, yperbasis commented on cmd/dbtool.cpp
> +struct stage_set_options_t {
For consistency with our style, please name it StageSetOptions

2021-07-13 21:03 UTC, Giulio2002 commented
Ready for review

2021-07-14 12:41 UTC, yperbasis approved these changes

2021-07-14 12:48 UTC, yperbasis commented
LGTM. @AndreaLanfranchi are you happy with the PR?

2021-07-14 15:20 UTC, AndreaLanfranchi requested changes

2021-07-14 15:21 UTC, AndreaLanfranchi commented
> LGTM. @AndreaLanfranchi are you happy with the PR?

Generally yes ... question for @Giulio2002 have you tried some unwind methods on a synced db and eventually reuse that db for normal syncing on Erigon ? Is the db still consistent ?

2021-07-15 07:39 UTC, yperbasis approved these changes

2021-07-15 07:49 UTC, merged