added unwind_tx_lookup
torquem-ch/silkworm pull request #300
Opened 2021-07-16 16:59 UTC by Giulio2002

2021-07-17 09:00 UTC, AndreaLanfranchi requested changes

2021-07-17 09:00 UTC, AndreaLanfranchi commented on db/silkworm/stagedsync/stage_tx_lookup.cpp
> +            }
Why this code duplication ?
```suggestion
            while (tx_data && tx_count < body.txn_count) {
                auto tx_view{db::from_slice(tx_data.value)};
                auto hash{keccak256(tx_view)};
                auto data{lookup_table.find(db::to_slice(hash.bytes), false)};
                if (data) {
                    lookup_table.erase();
                }
                ++tx_count;
                tx_data = transactions_table.to_next(/*throw_notfound*/ false);
            }
```

2021-07-17 09:17 UTC, AndreaLanfranchi requested changes

2021-07-17 09:17 UTC, AndreaLanfranchi commented on cmd/unwind_tx_lookup.cpp
> +    db::EnvConfig db_config{datadir};
db_config requires a string for initialization but you're using a fs::path

2021-07-17 09:47 UTC, AndreaLanfranchi commented on db/silkworm/stagedsync/stage_tx_lookup.cpp
> +            }
Also ... when you simply need to delete a record and you don't need data from that record use seek (which prevents an allocation of a data structure. Hence this is even better 
```suggestion
            while (tx_data && tx_count < body.txn_count) {
                auto tx_view{db::from_slice(tx_data.value)};
                auto hash{keccak256(tx_view)};
                if(lookup_table.seek(db::to_slice(hash.bytes)) {
                    lookup_table.erase();
                }
                ++tx_count;
                tx_data = transactions_table.to_next(/*throw_notfound*/ false);
            }
```

2021-07-20 07:11 UTC, yperbasis approved these changes

2021-07-20 07:43 UTC, AndreaLanfranchi approved these changes

2021-07-20 08:34 UTC, merged