added tests for hashstate
torquem-ch/silkworm pull request #354
Opened 2021-08-11 22:00 UTC by Giulio2002

2021-08-12 10:46 UTC, yperbasis requested changes
@Giulio2002 I've made a couple of fixes related to Issue #355, and now the test fails :( Could you investigate please.

2021-08-12 13:00 UTC, Giulio2002 commented
> @Giulio2002 I've made a couple of fixes related to Issue #355, and now the test fails :( Could you investigate please.

On my way🕵️

2021-08-12 13:49 UTC, Giulio2002 commented
Now it's fixed @yperbasis

2021-08-12 14:35 UTC, yperbasis commented on node/silkworm/stagedsync/stage_hashstate_test.cpp
> +    CHECK(hashed_address_table.seek(db::to_slice(address_keccak)));
Please also check the value of the account.

2021-08-13 08:12 UTC, yperbasis approved these changes

2021-08-13 08:13 UTC, merged