Chain config consistency with hardcoded one
torquem-ch/silkworm pull request #730
Opened 2022-08-12 16:29 UTC by AndreaLanfranchi

Should new forkblocks be added persisted config should be updated to hardcoded one.

Fixes #717

2022-08-15 16:45 UTC, canepat requested changes

2022-08-15 16:45 UTC, canepat commented on cmd/common.cpp
> +                node_settings.chain_config = db::read_chain_config(*tx);
Is there a specific reason to read chain config again after update instead of using `known_chain->second`?

2022-08-15 16:45 UTC, canepat commented on wasm/silkworm_wasm_api.cpp
> +const ChainConfig* lookup_config(uint64_t chain_id) { return lookup_known_chain(chain_id)->second; }
`lookup_known_chain` can return `std::nullopt`, so I suggest to change this function body to:
```
const auto chain{lookup_known_chain(chain_id)};
if (!chain) {
    return nullptr;
}
return chain->second;
```

2022-08-15 17:19 UTC, AndreaLanfranchi commented on cmd/backend_kv_server.cpp
> +    auto known_chain_config{silkworm::lookup_known_chain(node_settings.network_id)};
Ok I resolved that but I wanted to point out that `backend_kv_server` actuallly uses the config from the known set while instead should retrieve it from the primed db cause we might have custom chains configured.

2022-08-16 06:36 UTC, canepat commented on cmd/backend_kv_server.cpp
> +    auto known_chain_config{silkworm::lookup_known_chain(node_settings.network_id)};
Opened issue #732

2022-08-16 06:36 UTC, canepat submitted a review, later dismissed

2022-08-16 13:27 UTC, AndreaLanfranchi commented
@canepat I forgot to introduce a check on existing members and their respective activation.
Existing config members might be legitimately or mistakenly changed.
Re-requesting your review.

2022-08-17 21:41 UTC, canepat approved these changes

2022-08-17 22:06 UTC, merged